### ISSUE TITLE
When no category in race, no possible to enter race

### ISSUE THREAD

**Issue by xkenia** [sokolpezinok/orientacny-beh#1] opened 2023-10-11 19:12 UTC
When there is no category in race, there is no possibility how to enter the race, because category is mandatory.

**Comment by jurakin** [comment] 2023-10-21 09:41
I'm closing the issue, the bug is fixed in version 2.0-beta.

The problem is solved as follows: if a list of categories is available, select is displayed, otherwise input is shown.

**Closed as completed by jurakin** 2023-10-21 09:41 UTC
